### ISSUE TITLE
SendConfigToFrontend on first startup.

### ISSUE THREAD

**Issue by ekaliclua** [NoxenScripts/noxen_notify#4]
Hello,

I've noticed that when the server starts and I join the server, the position configuration is not taken into account and I have to restart the server. Wouldn't it be better to use a thread instead of the start event? (I tried it on my side and it seems to work better.)

Ekali.

**Comment by desperadisse** [comment]
Hello Ekali,

Thank you for bringing this issue to our attention and for your suggestion. Using a thread instead of the start event does indeed seem like a viable solution to ensure that the position configuration is applied when the server starts.

If you'd like, please feel free to submit a pull request with your implementation. It could benefit the entire community.

Thanks again for your contribution!
